const herbs = [
     
[
  {"name":"Alfalfa","categories":["nutrient-rich","detox"],"supports":["nutrient_support","detoxification"],"contraindications":["autoimmune_conditions"],"synergy":["Nettle"]},
  {"name":"Anise","categories":["carminative","digestive"],"supports":["digestion","bloating"],"contraindications":["pregnancy"],"synergy":["Fennel"]},
  {"name":"Ashwagandha","categories":["adaptogen","nervine"],"supports":["stress","energy","sleep"],"contraindications":["pregnancy"],"synergy":["Rhodiola","Holy Basil","Ginseng"]},
  {"name":"Basil","categories":["nervine","digestive"],"supports":["digestion","stress"],"contraindications":[],"synergy":["Holy Basil"]},
  {"name":"Bay Leaf","categories":["digestive","antimicrobial"],"supports":["digestion","antioxidant_support"],"contraindications":[],"synergy":["Thyme","Rosemary"]},
  {"name":"Black Cohosh","categories":["hormonal","nervine"],"supports":["menopause_symptoms"],"contraindications":["pregnancy","liver_disease"],"synergy":["Red Clover"]},
  {"name":"Blue Vervain","categories":["nervine","digestive"],"supports":["stress","digestion"],"contraindications":["pregnancy"],"synergy":["Chamomile"]},
  {"name":"Burdock Root","categories":["detox","liver"],"supports":["liver_health","skin_health"],"contraindications":[],"synergy":["Dandelion"]},
  {"name":"Cardamom","categories":["digestive","carminative"],"supports":["digestion","bloating"],"contraindications":[],"synergy":["Ginger"]},
  {"name":"Cayenne","categories":["circulatory","digestive"],"supports":["circulation","digestion","pain"],"contraindications":["ulcers"],"synergy":["Ginger","Turmeric"]},
  {"name":"Catnip","categories":["nervine","digestive"],"supports":["sleep","digestion"],"contraindications":[],"synergy":["Chamomile"]},
  {"name":"Chamomile","categories":["nervine"],"supports":["sleep","anxiety","digestion"],"contraindications":[],"synergy":["Lemon Balm"]},
  {"name":"Chervil","categories":["digestive","carminative"],"supports":["digestion","detox"],"contraindications":[],"synergy":["Parsley"]},
  {"name":"Chaga","categories":["immune","antioxidant"],"supports":["immune_support","antioxidant_support"],"contraindications":[],"synergy":["Reishi"]},
  {"name":"Chicory","categories":["liver","digestive"],"supports":["liver_health","digestion"],"contraindications":[],"synergy":["Dandelion","Milk Thistle"]},
  {"name":"Cinnamon","categories":["digestive","circulatory"],"supports":["blood_sugar","digestion","circulation"],"contraindications":["liver_disease"],"synergy":["Ginger"]},
  {"name":"Coriander","categories":["digestive","carminative"],"supports":["digestion","detoxification"],"contraindications":[],"synergy":["Fennel"]},
  {"name":"Corn Silk","categories":["diuretic","digestive"],"supports":["kidney_health","digestion"],"contraindications":[],"synergy":["Nettle","Parsley"]},
  {"name":"Dandelion","categories":["diuretic","liver"],"supports":["liver_health","detox","digestion"],"contraindications":["gallstones"],"synergy":["Milk Thistle","Burdock Root","Nettle"]},
  {"name":"Echinacea","categories":["immune","antimicrobial"],"supports":["immune_support","infection"],"contraindications":["autoimmune_conditions"],"synergy":["Goldenseal","Pau d'Arco"]},
  {"name":"Fenugreek","categories":["hormonal","digestive"],"supports":["lactation_support","digestion"],"contraindications":["pregnancy"],"synergy":["Fennel"]},
  {"name":"Fennel","categories":["carminative","digestive"],"supports":["digestion","bloating","lactation_support"],"contraindications":["pregnancy"],"synergy":["Anise","Fenugreek"]},
  {"name":"Garlic","categories":["cardiovascular","immune"],"supports":["immune_support","blood_pressure","cholesterol"],"contraindications":["blood_thinners"],"synergy":["Ginger"]},
  {"name":"Ginkgo Biloba","categories":["cognitive","circulatory"],"supports":["memory","circulation","focus"],"contraindications":["blood_thinners"],"synergy":["Gotu Kola","Pine Bark","Hawthorn"]},
  {"name":"Ginger","categories":["carminative"],"supports":["digestion","bloating","inflammation"],"contraindications":[],"synergy":["Turmeric","Cayenne","Cinnamon","Peppermint","Cardamom"]},
  {"name":"Ginseng","categories":["adaptogen","energy"],"supports":["energy","stress","immune_support"],"contraindications":["high_blood_pressure"],"synergy":["Ashwagandha","Rhodiola","Cordyceps","Maca"]},
  {"name":"Goldenseal","categories":["immune","antimicrobial"],"supports":["infection","digestion"],"contraindications":["pregnancy","high_blood_pressure"],"synergy":["Echinacea"]},
  {"name":"Gotu Kola","categories":["cognitive","circulatory"],"supports":["memory","circulation","skin healing"],"contraindications":["liver_disease"],"synergy":["Ginkgo Biloba"]},
  {"name":"Hawthorn","categories":["cardiovascular"],"supports":["heart_health","circulation"],"contraindications":["hypotension"],"synergy":["Ginkgo Biloba","Hibiscus"]},
  {"name":"Hibiscus","categories":["cardiovascular","immune"],"supports":["blood_pressure","immune_support"],"contraindications":["pregnancy"],"synergy":["Hawthorn"]},
  {"name":"Horehound","categories":["respiratory","digestive"],"supports":["respiratory_health","digestion"],"contraindications":[],"synergy":["Mullein","Thyme"]},
  {"name":"Holy Basil","categories":["adaptogen","nervine"],"supports":["stress","anxiety","inflammation"],"contraindications":[],"synergy":["Ashwagandha","Basil"]},
  {"name":"Lavender","categories":["nervine","antimicrobial"],"supports":["sleep","anxiety","relaxation"],"contraindications":[],"synergy":["Chamomile","Lemon Balm"]},
  {"name":"Lemon Balm","categories":["nervine","antiviral"],"supports":["anxiety","sleep","mood"],"contraindications":[],"synergy":["Chamomile","Lavender"]},
  {"name":"Licorice Root","categories":["adaptogen","digestive"],"supports":["stress","digestion","adrenal_support"],"contraindications":["high_blood_pressure"],"synergy":["Ashwagandha"]},
  {"name":"Maca","categories":["adaptogen","hormonal"],"supports":["energy","hormonal_balance"],"contraindications":["thyroid_conditions"],"synergy":["Ginseng","Shatavari","Catuaba"]},
  {"name":"Marshmallow Root","categories":["mucilaginous","digestive"],"supports":["soothe_throat","digestion"],"contraindications":[],"synergy":["Slippery Elm"]},
  {"name":"Meadowsweet","categories":["anti-inflammatory","digestive"],"supports":["pain","digestion"],"contraindications":["pregnancy","blood_thinners"],"synergy":["Ginger","Turmeric"]},
  {"name":"Milk Thistle","categories":["liver","detox"],"supports":["liver_health","detoxification"],"contraindications":["allergy_to_silymarin"],"synergy":["Dandelion","Chicory","Thistle"]},
  {"name":"Moringa","categories":["nutrient-rich","adaptogen"],"supports":["energy","nutrition","immune_support"],"contraindications":[],"synergy":["Ashwagandha","Ginseng"]},
  {"name":"Mullein","categories":["respiratory"],"supports":["lung_health","cough"],"contraindications":[],"synergy":["Horehound"]},
  {"name":"Nettle","categories":["diuretic","nutrient-rich"],"supports":["allergies","detoxification","iron_support"],"contraindications":["kidney_disease"],"synergy":["Dandelion","Alfalfa","Parsley"]},
  {"name":"Oatstraw","categories":["nervine","mineral-rich"],"supports":["stress","nervous_system"],"contraindications":[],"synergy":["Chamomile","Lemon Balm"]},
  {"name":"Oregano","categories":["antimicrobial","digestive"],"supports":["immune_support","digestion"],"contraindications":[],"synergy":["Thyme"]},
  {"name":"Passionflower","categories":["nervine","sedative"],"supports":["sleep","anxiety"],"contraindications":["pregnancy"],"synergy":["Valerian","Chamomile"]},
  {"name":"Pau d'Arco","categories":["immune","antimicrobial"],"supports":["infection","immune_support"],"contraindications":["pregnancy"],"synergy":["Echinacea"]},
  {"name":"Peppermint","categories":["digestive","nervine"],"supports":["digestion","headache"],"contraindications":["GERD"],"synergy":["Ginger","Chamomile"]},
  {"name":"Pine Bark","categories":["circulatory","antioxidant"],"supports":["circulation","antioxidant_support"],"contraindications":[],"synergy":["Ginkgo Biloba"]},
  {"name":"Red Clover","categories":["hormonal","blood"],"supports":["menopause_support","circulation"],"contraindications":["hormone_sensitive_cancers"],"synergy":["Black Cohosh"]},
  {"name":"Reishi","categories":["immune","adaptogen"],"supports":["immune_support","stress"],"contraindications":[],"synergy":["Chaga","Ginseng"]},
  {"name":"Rhodiola","categories":["adaptogen","cognitive"],"supports":["energy","focus","stress"],"contraindications":["high_anxiety"],"synergy":["Ashwagandha","Ginseng"]},
  {"name":"Rosemary","categories":["cognitive","digestive"],"supports":["memory","digestion","circulation"],"contraindications":["pregnancy"],"synergy":["Sage","Bay Leaf"]},
  {"name":"Sage","categories":["cognitive","antimicrobial"],"supports":["memory","digestion","oral_health"],"contraindications":["pregnancy"],"synergy":["Rosemary"]},
  {"name":"Shatavari","categories":["adaptogen","hormonal"],"supports":["hormonal_balance","fertility"],"contraindications":["pregnancy"],"synergy":["Maca","Ashwagandha"]},
  {"name":"Skullcap","categories":["nervine","sedative"],"supports":["anxiety","sleep","nervous_tension"],"contraindications":[],"synergy":["Chamomile","Lemon Balm"]},
  {"name":"Slippery Elm","categories":["mucilaginous","digestive"],"supports":["soothe_throat","digestion"],"contraindications":[],"synergy":["Marshmallow Root"]},
  {"name":"Spearmint","categories":["digestive","nervine"],"supports":["digestion","stress"],"contraindications":[],"synergy":["Peppermint"]},
  {"name":"St. John's Wort","categories":["antidepressant","nervine"],"supports":["mood","anxiety"],"contraindications":["SSRIs","pregnancy","photosensitivity"],"synergy":["Lemon Balm","Saffron"]},
  {"name":"Thyme","categories":["antimicrobial","respiratory"],"supports":["respiratory_health","immune_support"],"contraindications":[],"synergy":["Oregano","Bay Leaf","Horehound"]},
  {"name":"Tarragon","categories":["digestive","carminative"],"supports":["digestion","appetite"],"contraindications":[],"synergy":["Fennel"]},
  {"name":"Turmeric","categories":["anti-inflammatory","liver"],"supports":["inflammation","joint health","digestion"],"contraindications":["gallstones"],"synergy":["Ginger","Cayenne","Meadowsweet"]},
  {"name":"Valerian","categories":["nervine","sedative"],"supports":["sleep","anxiety"],"contraindications":["pregnancy","liver_disease"],"synergy":["Chamomile","Lemon Balm"]},
  {"name":"Yarrow","categories":["circulatory","anti-inflammatory"],"supports":["wound_healing","circulation","fever"],"contraindications":["pregnancy"],"synergy":["Chamomile"]},
  {"name":"Yohimbe","categories":["circulatory","energy"],"supports":["energy","circulation"],"contraindications":["high_blood_pressure","heart_conditions"],"synergy":["Ginseng"]},
  {"name":"Albizia","categories":["nervine","mood"],"supports":["mood","grief","anxiety"],"contraindications":["pregnancy"],"synergy":["Lemon Balm","St. John's Wort"]},
  {"name":"Andrographis","categories":["immune","antiviral"],"supports":["immune_support","infection"],"contraindications":["pregnancy"],"synergy":["Echinacea","Astragalus"]},
  {"name":"Arjuna","categories":["cardiovascular"],"supports":["heart_health","circulation"],"contraindications":[],"synergy":["Hawthorn"]},
  {"name":"Artichoke Leaf","categories":["digestive","liver"],"supports":["liver_health","digestion","bloating"],"contraindications":["gallstones"],"synergy":["Dandelion","Milk Thistle"]},
  {"name":"Astragalus","categories":["immune","adaptogen"],"supports":["immune_support","energy"],"contraindications":["acute_infection"],"synergy":["Reishi","Echinacea"]},
  {"name":"Bacopa","categories":["cognitive","adaptogen"],"supports":["memory","focus","stress"],"contraindications":["pregnancy"],"synergy":["Ginkgo Biloba","Rhodiola"]},
  {"name":"Bilberry","categories":["circulatory","antioxidant"],"supports":["eye_health","circulation","blood_sugar"],"contraindications":["blood_thinners"],"synergy":["Pine Bark","Ginkgo Biloba"]},
  {"name":"Bitter Melon","categories":["metabolic"],"supports":["blood_sugar","metabolism"],"contraindications":["pregnancy"],"synergy":["Gymnema","Cinnamon"]},
  {"name":"Boswellia","categories":["anti-inflammatory"],"supports":["joint_health","inflammation"],"contraindications":[],"synergy":["Turmeric","Ginger"]},
  {"name":"Butcher's Broom","categories":["circulatory"],"supports":["circulation","vein_health"],"contraindications":["high_blood_pressure"],"synergy":["Horse Chestnut"]},
  {"name":"Calendula","categories":["lymphatic","skin"],"supports":["wound_healing","lymphatic_support","skin_health"],"contraindications":[],"synergy":["Cleavers","Plantain"]},
  {"name":"Cat's Claw","categories":["immune","anti-inflammatory"],"supports":["immune_support","joint_health"],"contraindications":["pregnancy","autoimmune_conditions"],"synergy":["Reishi"]},
  {"name":"Cleavers","categories":["lymphatic","diuretic"],"supports":["lymphatic_support","skin_health"],"contraindications":[],"synergy":["Calendula","Red Root"]},
  {"name":"Coltsfoot","categories":["respiratory"],"supports":["cough","lung_health"],"contraindications":["pregnancy","liver_disease"],"synergy":["Mullein"]},
  {"name":"Cramp Bark","categories":["antispasmodic","women's_health"],"supports":["menstrual_cramps","muscle_spasm"],"contraindications":["pregnancy"],"synergy":["Black Cohosh"]},
  {"name":"Damiana","categories":["nervine","reproductive"],"supports":["mood","libido"],"contraindications":["pregnancy"],"synergy":["Maca","Muira Puama"]},
  {"name":"Devil's Claw","categories":["anti-inflammatory"],"supports":["joint_health","pain"],"contraindications":["ulcers"],"synergy":["Turmeric","Boswellia"]},
  {"name":"Dong Quai","categories":["hormonal","circulatory"],"supports":["menstrual_health","circulation"],"contraindications":["pregnancy","blood_thinners"],"synergy":["Vitex","Red Clover"]},
  {"name":"Elderberry","categories":["immune","antiviral"],"supports":["immune_support","infection"],"contraindications":["autoimmune_conditions"],"synergy":["Echinacea","Andrographis"]},
  {"name":"Elderflower","categories":["immune","respiratory"],"supports":["fever","respiratory_health"],"contraindications":[],"synergy":["Yarrow","Peppermint"]},
  {"name":"Elecampane","categories":["respiratory"],"supports":["cough","lung_health"],"contraindications":["pregnancy"],"synergy":["Mullein","Thyme"]},
  {"name":"Gentian","categories":["digestive","bitter"],"supports":["digestion","appetite"],"contraindications":["ulcers"],"synergy":["Dandelion","Artichoke Leaf"]},
  {"name":"Gymnema","categories":["metabolic"],"supports":["blood_sugar","cravings"],"contraindications":["pregnancy"],"synergy":["Bitter Melon","Cinnamon"]},
  {"name":"Hyssop","categories":["respiratory","antimicrobial"],"supports":["respiratory_health","immune_support"],"contraindications":["pregnancy"],"synergy":["Thyme"]},
  {"name":"Kava","categories":["nervine","sedative"],"supports":["anxiety","muscle_tension"],"contraindications":["liver_disease","pregnancy"],"synergy":["Passionflower","Valerian"]},
  {"name":"Lady's Mantle","categories":["women's_health"],"supports":["menstrual_balance","reproductive_health"],"contraindications":["pregnancy"],"synergy":["Red Clover"]},
  {"name":"Linden","categories":["nervine","cardiovascular"],"supports":["stress","blood_pressure"],"contraindications":[],"synergy":["Hawthorn","Chamomile"]},
  {"name":"Lion's Mane","categories":["cognitive","immune"],"supports":["memory","nerve_regeneration","immune_support"],"contraindications":[],"synergy":["Reishi","Bacopa"]},
  {"name":"Lobelia","categories":["respiratory","antispasmodic"],"supports":["respiratory_health","muscle_spasm"],"contraindications":["pregnancy"],"synergy":["Mullein"]},
  {"name":"Motherwort","categories":["nervine","cardiovascular"],"supports":["anxiety","heart_health","menstrual_support"],"contraindications":["pregnancy"],"synergy":["Hawthorn","Linden"]},
  {"name":"Muira Puama","categories":["reproductive","energy"],"supports":["libido","energy"],"contraindications":["pregnancy"],"synergy":["Damiana","Maca"]},
  {"name":"Neem","categories":["antimicrobial","skin"],"supports":["skin_health","immune_support"],"contraindications":["pregnancy"],"synergy":["Calendula"]},
  {"name":"Olive Leaf","categories":["antimicrobial","cardiovascular"],"supports":["immune_support","blood_pressure"],"contraindications":["low_blood_pressure"],"synergy":["Hawthorn","Elderberry"]},
  {"name":"Oregon Grape Root","categories":["liver","antimicrobial"],"supports":["liver_health","skin_health"],"contraindications":["pregnancy"],"synergy":["Dandelion","Burdock Root"]},
  {"name":"Plantain","categories":["respiratory","skin"],"supports":["wound_healing","respiratory_health"],"contraindications":[],"synergy":["Calendula","Mullein"]},
  {"name":"Red Root","categories":["lymphatic"],"supports":["lymphatic_support","immune_support"],"contraindications":["pregnancy"],"synergy":["Cleavers"]},
  {"name":"Saw Palmetto","categories":["reproductive","men's_health"],"supports":["prostate_health","hormonal_balance"],"contraindications":["pregnancy"],"synergy":["Nettle"]},
  {"name":"Schisandra","categories":["adaptogen","liver"],"supports":["stress","liver_health","energy"],"contraindications":["pregnancy"],"synergy":["Rhodiola","Milk Thistle"]},
  {"name":"Tribulus","categories":["reproductive","energy"],"supports":["libido","hormonal_balance"],"contraindications":["pregnancy"],"synergy":["Maca"]},
  {"name":"Usnea","categories":["antimicrobial","immune"],"supports":["infection","immune_support"],"contraindications":["pregnancy"],"synergy":["Echinacea"]},
  {"name":"Vitex","categories":["hormonal","women's_health"],"supports":["menstrual_balance","fertility"],"contraindications":["pregnancy"],"synergy":["Dong Quai","Red Clover"]},
  {"name":"White Willow Bark","categories":["anti-inflammatory","analgesic"],"supports":["pain","inflammation"],"contraindications":["pregnancy","blood_thinners"],"synergy":["Meadowsweet","Turmeric"]},
  {"name":"Wild Yam","categories":["hormonal","digestive"],"supports":["menstrual_support","digestion"],"contraindications":["pregnancy"],"synergy":["Black Cohosh"]}
]


];